// @flow

export const Level = Object.freeze({
  H: 'h',
  M: 'm',
  L: 'l',
  STROBE: 'strobe',
});
export type LevelType = $Values<typeof Level>;

// The prefix tells you what setting the light is at.
export const StatePrefix = Object.freeze({
  // H levels - H1 and the three sublevels possible for H2.
  H1: 'h1',
  H2_1: 'h2.1',
  H2_2: 'h2.2',
  H2_3: 'h2.3',

  M1: 'm1',
  M2_1: 'm2.1',
  M2_2: 'm2.2',
  M2_3: 'm2.3',

  L1: 'l1',
  L2_1: 'l2.1',
  L2_2: 'l2.2',
  L2_3: 'l2.3',

  STROBE1_1: 'strobe1.1',
  STROBE1_2: 'strobe1.2',
  STROBE1_3: 'strobe1.3',
  STROBE1_4: 'strobe1.4',
});
export type StatePrefixType = $Values<typeof StatePrefix>;

// The suffix keeps track of different states within each light setting.
export const StateSuffix = Object.freeze({
  CYCLE: 'cycle',
  CYCLE_PRE_H: 'cycle_pre_h',
  CYCLE_PRE_M: 'cycle_pre_m',
  CYCLE_PRE_STROBE: 'cycle_pre_strobe',
  CYCLE_STROBE_BEAT: 'cycle_strobe_beat',
  CYCLE_PRE_BATTERY_INDICATOR: 'cycle_pre_battery_indicator',

  STABLE: 'stable',

  TOGGLE_INTERMEDIATE_1: 'toggle_intermediate_1',
  TOGGLE_1: 'toggle_1',
  TOGGLE_INTERMEDIATE_2: 'toggle_intermediate_2',
  TOGGLE_2: 'toggle_2',
  TOGGLE_INTERMEDIATE_3: 'toggle_intermediate_3',
  TOGGLE_3: 'toggle_3',
  TOGGLE_INTERMEDIATE_4: 'toggle_intermediate_4',
  TOGGLE_4: 'toggle_4',
  TOGGLE_INTERMEDIATE_5: 'toggle_intermediate_5',
  TOGGLE_5: 'toggle_5',
  TOGGLE_INTERMEDIATE_6: 'toggle_intermediate_6',
  TOGGLE_6: 'toggle_6',
  TOGGLE_INTERMEDIATE_7: 'toggle_intermediate_7',

  SUBCYCLE_INTERMEDIATE: 'subcycle_intermediate',
  SUBCYCLE: 'subcycle',
});
export type StateSuffixType = $Values<typeof StateSuffix>;

// Transition descriptions by example:
// [push] push start
// (<= 0.5s later) [release] short_press_release
// (0.5s later) multi_single_press_timeout
// (11.5s later, 12s after release) multi_double_press_timeout

// [push] push start
// (0.5s later) long_press_beat
// (0.5s later) long_press_beat
// (0.2s later) [release] long_press_release

// battery_indicator_finished fires after blinking 1-4 times to indicate
// battery life remaining.

export const Transition = Object.freeze({
  PRESS_START: 'press_start',
  SHORT_PRESS_RELEASE: 'short_press_release',
  LONG_PRESS_BEAT: 'long_press_beat',
  LONG_PRESS_RELEASE: 'long_press_release',
  MULTI_SINGLE_PRESS_TIMEOUT: 'multi_single_press_timeout',
  MULTI_DOUBLE_PRESS_TIMEOUT: 'multi_double_press_timeout',
  BATTERY_INDICATOR_FINISHED: 'battery_indicator_finished',
});
export type TransitionType = $Values<typeof Transition>;

export const MemoryVariable = Object.freeze({
  // 1 if sublevel 2 was last used, or 2 if sublevel 2 was last used.
  H_LAST_USED: 'h.last_used',
  M_LAST_USED: 'm.last_used',
  L_LAST_USED: 'l.last_used',

  // The programmed setting for (1, 2, or 3) for sublevel 2.
  H2_OPTION: 'h2.option',
  M2_OPTION: 'm2.option',
  L2_OPTION: 'l2.option',
  STROBE_OPTION: 'strobe1.option',
});
export type MemoryVariableType = $Values<typeof MemoryVariable>;

export const State = Object.freeze({
  OFF: 'off',
  BATTERY_INDICATOR: 'battery_indicator',

  H1_STABLE: 'h1.stable',
  H2_1_STABLE: 'h2.1.stable',
  H2_2_STABLE: 'h2.2.stable',
  H2_3_STABLE: 'h2.3.stable',
  M1_STABLE: 'm1.stable',
  M2_1_STABLE: 'm2.1.stable',
  M2_2_STABLE: 'm2.2.stable',
  M2_3_STABLE: 'm2.3.stable',
  L1_STABLE: 'l1.stable',
  L2_1_STABLE: 'l2.1.stable',
  L2_2_STABLE: 'l2.2.stable',
  L2_3_STABLE: 'l2.3.stable',

  H1_CYCLE: 'h1.cycle',
  H2_1_CYCLE: 'h2.1.cycle',
  H2_2_CYCLE: 'h2.2.cycle',
  H2_3_CYCLE: 'h2.3.cycle',
  M1_CYCLE: 'm1.cycle',
  M2_1_CYCLE: 'm2.1.cycle',
  M2_2_CYCLE: 'm2.2.cycle',
  M2_3_CYCLE: 'm2.3.cycle',
  L1_CYCLE: 'l1.cycle',
  L2_1_CYCLE: 'l2.1.cycle',
  L2_2_CYCLE: 'l2.2.cycle',
  L2_3_CYCLE: 'l2.3.cycle',

  // There is an extra beat on low when first turning on the light from off,
  // and the light switches back to low on pressing when cycling with short
  // presses.
  L1_CYCLE_PRE_H: 'l1.cycle_pre_h',
  L2_1_CYCLE_PRE_H: 'l2.1.cycle_pre_h',
  L2_2_CYCLE_PRE_H: 'l2.2.cycle_pre_h',
  L2_3_CYCLE_PRE_H: 'l2.3.cycle_pre_h',
  L1_CYCLE_PRE_M: 'l1.cycle_pre_m',
  L2_1_CYCLE_PRE_M: 'l2.1.cycle_pre_m',
  L2_2_CYCLE_PRE_M: 'l2.2.cycle_pre_m',
  L2_3_CYCLE_PRE_M: 'l2.3.cycle_pre_m',
  L1_CYCLE_PRE_STROBE: 'l1.cycle_pre_strobe',
  L2_1_CYCLE_PRE_STROBE: 'l2.1.cycle_pre_strobe',
  L2_2_CYCLE_PRE_STROBE: 'l2.2.cycle_pre_strobe',
  L2_3_CYCLE_PRE_STROBE: 'l2.3.cycle_pre_strobe',

  // There is an extra beat on the strobe setting at low before the strobe
  // starts.
  L1_CYCLE_STROBE_BEAT: 'l1.cycle_strobe_beat',
  L2_1_CYCLE_STROBE_BEAT: 'l2.1.cycle_strobe_beat',
  L2_2_CYCLE_STROBE_BEAT: 'l2.2.cycle_strobe_beat',
  L2_3_CYCLE_STROBE_BEAT: 'l2.3.cycle_strobe_beat',
  L1_CYCLE_PRE_BATTERY_INDICATOR: 'l1.cycle_pre_battery_indicator',
  L2_1_CYCLE_PRE_BATTERY_INDICATOR: 'l2.1.cycle_pre_battery_indicator',
  L2_2_CYCLE_PRE_BATTERY_INDICATOR: 'l2.2.cycle_pre_battery_indicator',
  L2_3_CYCLE_PRE_BATTERY_INDICATOR: 'l2.3.cycle_pre_battery_indicator',

  H1_TOGGLE_INTERMEDIATE_1: 'h1.toggle_intermediate_1',
  H1_TOGGLE_1: 'h1.toggle_1',
  H1_TOGGLE_INTERMEDIATE_2: 'h1.toggle_intermediate_2',
  H1_TOGGLE_2: 'h1.toggle_2',
  H1_TOGGLE_INTERMEDIATE_3: 'h1.toggle_intermediate_3',
  H1_TOGGLE_3: 'h1.toggle_3',
  H1_TOGGLE_INTERMEDIATE_4: 'h1.toggle_intermediate_4',
  H1_TOGGLE_4: 'h1.toggle_4',
  H1_TOGGLE_INTERMEDIATE_5: 'h1.toggle_intermediate_5',
  H1_TOGGLE_5: 'h1.toggle_5',
  H1_TOGGLE_INTERMEDIATE_6: 'h1.toggle_intermediate_6',
  H1_TOGGLE_6: 'h1.toggle_6',
  H1_TOGGLE_INTERMEDIATE_7: 'h1.toggle_intermediate_7',
  H1_SUBCYCLE_INTERMEDIATE: 'h1.subcycle_intermediate',
  H1_SUBCYCLE: 'h1.subcycle',
  H2_1_TOGGLE_INTERMEDIATE_1: 'h2.1.toggle_intermediate_1',
  H2_1_TOGGLE_1: 'h2.1.toggle_1',
  H2_1_TOGGLE_INTERMEDIATE_2: 'h2.1.toggle_intermediate_2',
  H2_1_TOGGLE_2: 'h2.1.toggle_2',
  H2_1_TOGGLE_INTERMEDIATE_3: 'h2.1.toggle_intermediate_3',
  H2_1_TOGGLE_3: 'h2.1.toggle_3',
  H2_1_TOGGLE_INTERMEDIATE_4: 'h2.1.toggle_intermediate_4',
  H2_1_TOGGLE_4: 'h2.1.toggle_4',
  H2_1_TOGGLE_INTERMEDIATE_5: 'h2.1.toggle_intermediate_5',
  H2_1_TOGGLE_5: 'h2.1.toggle_5',
  H2_1_TOGGLE_INTERMEDIATE_6: 'h2.1.toggle_intermediate_6',
  H2_1_TOGGLE_6: 'h2.1.toggle_6',
  H2_1_TOGGLE_INTERMEDIATE_7: 'h2.1.toggle_intermediate_7',
  H2_1_SUBCYCLE_INTERMEDIATE: 'h2.1.subcycle_intermediate',
  H2_1_SUBCYCLE: 'h2.1.subcycle',
  H2_2_TOGGLE_INTERMEDIATE_1: 'h2.2.toggle_intermediate_1',
  H2_2_TOGGLE_1: 'h2.2.toggle_1',
  H2_2_TOGGLE_INTERMEDIATE_2: 'h2.2.toggle_intermediate_2',
  H2_2_TOGGLE_2: 'h2.2.toggle_2',
  H2_2_TOGGLE_INTERMEDIATE_3: 'h2.2.toggle_intermediate_3',
  H2_2_TOGGLE_3: 'h2.2.toggle_3',
  H2_2_TOGGLE_INTERMEDIATE_4: 'h2.2.toggle_intermediate_4',
  H2_2_TOGGLE_4: 'h2.2.toggle_4',
  H2_2_TOGGLE_INTERMEDIATE_5: 'h2.2.toggle_intermediate_5',
  H2_2_TOGGLE_5: 'h2.2.toggle_5',
  H2_2_TOGGLE_INTERMEDIATE_6: 'h2.2.toggle_intermediate_6',
  H2_2_TOGGLE_6: 'h2.2.toggle_6',
  H2_2_TOGGLE_INTERMEDIATE_7: 'h2.2.toggle_intermediate_7',
  H2_2_SUBCYCLE_INTERMEDIATE: 'h2.2.subcycle_intermediate',
  H2_2_SUBCYCLE: 'h2.2.subcycle',
  H2_3_TOGGLE_INTERMEDIATE_1: 'h2.3.toggle_intermediate_1',
  H2_3_TOGGLE_1: 'h2.3.toggle_1',
  H2_3_TOGGLE_INTERMEDIATE_2: 'h2.3.toggle_intermediate_2',
  H2_3_TOGGLE_2: 'h2.3.toggle_2',
  H2_3_TOGGLE_INTERMEDIATE_3: 'h2.3.toggle_intermediate_3',
  H2_3_TOGGLE_3: 'h2.3.toggle_3',
  H2_3_TOGGLE_INTERMEDIATE_4: 'h2.3.toggle_intermediate_4',
  H2_3_TOGGLE_4: 'h2.3.toggle_4',
  H2_3_TOGGLE_INTERMEDIATE_5: 'h2.3.toggle_intermediate_5',
  H2_3_TOGGLE_5: 'h2.3.toggle_5',
  H2_3_TOGGLE_INTERMEDIATE_6: 'h2.3.toggle_intermediate_6',
  H2_3_TOGGLE_6: 'h2.3.toggle_6',
  H2_3_TOGGLE_INTERMEDIATE_7: 'h2.3.toggle_intermediate_7',
  H2_3_SUBCYCLE_INTERMEDIATE: 'h2.3.subcycle_intermediate',
  H2_3_SUBCYCLE: 'h2.3.subcycle',
  M1_TOGGLE_INTERMEDIATE_1: 'm1.toggle_intermediate_1',
  M1_TOGGLE_1: 'm1.toggle_1',
  M1_TOGGLE_INTERMEDIATE_2: 'm1.toggle_intermediate_2',
  M1_TOGGLE_2: 'm1.toggle_2',
  M1_TOGGLE_INTERMEDIATE_3: 'm1.toggle_intermediate_3',
  M1_TOGGLE_3: 'm1.toggle_3',
  M1_TOGGLE_INTERMEDIATE_4: 'm1.toggle_intermediate_4',
  M1_TOGGLE_4: 'm1.toggle_4',
  M1_TOGGLE_INTERMEDIATE_5: 'm1.toggle_intermediate_5',
  M1_TOGGLE_5: 'm1.toggle_5',
  M1_TOGGLE_INTERMEDIATE_6: 'm1.toggle_intermediate_6',
  M1_TOGGLE_6: 'm1.toggle_6',
  M1_TOGGLE_INTERMEDIATE_7: 'm1.toggle_intermediate_7',
  M1_SUBCYCLE_INTERMEDIATE: 'm1.subcycle_intermediate',
  M1_SUBCYCLE: 'm1.subcycle',
  M2_1_TOGGLE_INTERMEDIATE_1: 'm2.1.toggle_intermediate_1',
  M2_1_TOGGLE_1: 'm2.1.toggle_1',
  M2_1_TOGGLE_INTERMEDIATE_2: 'm2.1.toggle_intermediate_2',
  M2_1_TOGGLE_2: 'm2.1.toggle_2',
  M2_1_TOGGLE_INTERMEDIATE_3: 'm2.1.toggle_intermediate_3',
  M2_1_TOGGLE_3: 'm2.1.toggle_3',
  M2_1_TOGGLE_INTERMEDIATE_4: 'm2.1.toggle_intermediate_4',
  M2_1_TOGGLE_4: 'm2.1.toggle_4',
  M2_1_TOGGLE_INTERMEDIATE_5: 'm2.1.toggle_intermediate_5',
  M2_1_TOGGLE_5: 'm2.1.toggle_5',
  M2_1_TOGGLE_INTERMEDIATE_6: 'm2.1.toggle_intermediate_6',
  M2_1_TOGGLE_6: 'm2.1.toggle_6',
  M2_1_TOGGLE_INTERMEDIATE_7: 'm2.1.toggle_intermediate_7',
  M2_1_SUBCYCLE_INTERMEDIATE: 'm2.1.subcycle_intermediate',
  M2_1_SUBCYCLE: 'm2.1.subcycle',
  M2_2_TOGGLE_INTERMEDIATE_1: 'm2.2.toggle_intermediate_1',
  M2_2_TOGGLE_1: 'm2.2.toggle_1',
  M2_2_TOGGLE_INTERMEDIATE_2: 'm2.2.toggle_intermediate_2',
  M2_2_TOGGLE_2: 'm2.2.toggle_2',
  M2_2_TOGGLE_INTERMEDIATE_3: 'm2.2.toggle_intermediate_3',
  M2_2_TOGGLE_3: 'm2.2.toggle_3',
  M2_2_TOGGLE_INTERMEDIATE_4: 'm2.2.toggle_intermediate_4',
  M2_2_TOGGLE_4: 'm2.2.toggle_4',
  M2_2_TOGGLE_INTERMEDIATE_5: 'm2.2.toggle_intermediate_5',
  M2_2_TOGGLE_5: 'm2.2.toggle_5',
  M2_2_TOGGLE_INTERMEDIATE_6: 'm2.2.toggle_intermediate_6',
  M2_2_TOGGLE_6: 'm2.2.toggle_6',
  M2_2_TOGGLE_INTERMEDIATE_7: 'm2.2.toggle_intermediate_7',
  M2_2_SUBCYCLE_INTERMEDIATE: 'm2.2.subcycle_intermediate',
  M2_2_SUBCYCLE: 'm2.2.subcycle',
  M2_3_TOGGLE_INTERMEDIATE_1: 'm2.3.toggle_intermediate_1',
  M2_3_TOGGLE_1: 'm2.3.toggle_1',
  M2_3_TOGGLE_INTERMEDIATE_2: 'm2.3.toggle_intermediate_2',
  M2_3_TOGGLE_2: 'm2.3.toggle_2',
  M2_3_TOGGLE_INTERMEDIATE_3: 'm2.3.toggle_intermediate_3',
  M2_3_TOGGLE_3: 'm2.3.toggle_3',
  M2_3_TOGGLE_INTERMEDIATE_4: 'm2.3.toggle_intermediate_4',
  M2_3_TOGGLE_4: 'm2.3.toggle_4',
  M2_3_TOGGLE_INTERMEDIATE_5: 'm2.3.toggle_intermediate_5',
  M2_3_TOGGLE_5: 'm2.3.toggle_5',
  M2_3_TOGGLE_INTERMEDIATE_6: 'm2.3.toggle_intermediate_6',
  M2_3_TOGGLE_6: 'm2.3.toggle_6',
  M2_3_TOGGLE_INTERMEDIATE_7: 'm2.3.toggle_intermediate_7',
  M2_3_SUBCYCLE_INTERMEDIATE: 'm2.3.subcycle_intermediate',
  M2_3_SUBCYCLE: 'm2.3.subcycle',
  L1_TOGGLE_INTERMEDIATE_1: 'l1.toggle_intermediate_1',
  L1_TOGGLE_1: 'l1.toggle_1',
  L1_TOGGLE_INTERMEDIATE_2: 'l1.toggle_intermediate_2',
  L1_TOGGLE_2: 'l1.toggle_2',
  L1_TOGGLE_INTERMEDIATE_3: 'l1.toggle_intermediate_3',
  L1_TOGGLE_3: 'l1.toggle_3',
  L1_TOGGLE_INTERMEDIATE_4: 'l1.toggle_intermediate_4',
  L1_TOGGLE_4: 'l1.toggle_4',
  L1_TOGGLE_INTERMEDIATE_5: 'l1.toggle_intermediate_5',
  L1_TOGGLE_5: 'l1.toggle_5',
  L1_TOGGLE_INTERMEDIATE_6: 'l1.toggle_intermediate_6',
  L1_TOGGLE_6: 'l1.toggle_6',
  L1_TOGGLE_INTERMEDIATE_7: 'l1.toggle_intermediate_7',
  L1_SUBCYCLE_INTERMEDIATE: 'l1.subcycle_intermediate',
  L1_SUBCYCLE: 'l1.subcycle',
  L2_1_TOGGLE_INTERMEDIATE_1: 'l2.1.toggle_intermediate_1',
  L2_1_TOGGLE_1: 'l2.1.toggle_1',
  L2_1_TOGGLE_INTERMEDIATE_2: 'l2.1.toggle_intermediate_2',
  L2_1_TOGGLE_2: 'l2.1.toggle_2',
  L2_1_TOGGLE_INTERMEDIATE_3: 'l2.1.toggle_intermediate_3',
  L2_1_TOGGLE_3: 'l2.1.toggle_3',
  L2_1_TOGGLE_INTERMEDIATE_4: 'l2.1.toggle_intermediate_4',
  L2_1_TOGGLE_4: 'l2.1.toggle_4',
  L2_1_TOGGLE_INTERMEDIATE_5: 'l2.1.toggle_intermediate_5',
  L2_1_TOGGLE_5: 'l2.1.toggle_5',
  L2_1_TOGGLE_INTERMEDIATE_6: 'l2.1.toggle_intermediate_6',
  L2_1_TOGGLE_6: 'l2.1.toggle_6',
  L2_1_TOGGLE_INTERMEDIATE_7: 'l2.1.toggle_intermediate_7',
  L2_1_SUBCYCLE_INTERMEDIATE: 'l2.1.subcycle_intermediate',
  L2_1_SUBCYCLE: 'l2.1.subcycle',
  L2_2_TOGGLE_INTERMEDIATE_1: 'l2.2.toggle_intermediate_1',
  L2_2_TOGGLE_1: 'l2.2.toggle_1',
  L2_2_TOGGLE_INTERMEDIATE_2: 'l2.2.toggle_intermediate_2',
  L2_2_TOGGLE_2: 'l2.2.toggle_2',
  L2_2_TOGGLE_INTERMEDIATE_3: 'l2.2.toggle_intermediate_3',
  L2_2_TOGGLE_3: 'l2.2.toggle_3',
  L2_2_TOGGLE_INTERMEDIATE_4: 'l2.2.toggle_intermediate_4',
  L2_2_TOGGLE_4: 'l2.2.toggle_4',
  L2_2_TOGGLE_INTERMEDIATE_5: 'l2.2.toggle_intermediate_5',
  L2_2_TOGGLE_5: 'l2.2.toggle_5',
  L2_2_TOGGLE_INTERMEDIATE_6: 'l2.2.toggle_intermediate_6',
  L2_2_TOGGLE_6: 'l2.2.toggle_6',
  L2_2_TOGGLE_INTERMEDIATE_7: 'l2.2.toggle_intermediate_7',
  L2_2_SUBCYCLE_INTERMEDIATE: 'l2.2.subcycle_intermediate',
  L2_2_SUBCYCLE: 'l2.2.subcycle',
  L2_3_TOGGLE_INTERMEDIATE_1: 'l2.3.toggle_intermediate_1',
  L2_3_TOGGLE_1: 'l2.3.toggle_1',
  L2_3_TOGGLE_INTERMEDIATE_2: 'l2.3.toggle_intermediate_2',
  L2_3_TOGGLE_2: 'l2.3.toggle_2',
  L2_3_TOGGLE_INTERMEDIATE_3: 'l2.3.toggle_intermediate_3',
  L2_3_TOGGLE_3: 'l2.3.toggle_3',
  L2_3_TOGGLE_INTERMEDIATE_4: 'l2.3.toggle_intermediate_4',
  L2_3_TOGGLE_4: 'l2.3.toggle_4',
  L2_3_TOGGLE_INTERMEDIATE_5: 'l2.3.toggle_intermediate_5',
  L2_3_TOGGLE_5: 'l2.3.toggle_5',
  L2_3_TOGGLE_INTERMEDIATE_6: 'l2.3.toggle_intermediate_6',
  L2_3_TOGGLE_6: 'l2.3.toggle_6',
  L2_3_TOGGLE_INTERMEDIATE_7: 'l2.3.toggle_intermediate_7',
  L2_3_SUBCYCLE_INTERMEDIATE: 'l2.3.subcycle_intermediate',
  L2_3_SUBCYCLE: 'l2.3.subcycle',

  STROBE1_1_SUBCYCLE_INTERMEDIATE: 'strobe1.1.subcycle_intermediate',
  STROBE1_1_SUBCYCLE: 'strobe1.1.subcycle',
  STROBE1_2_SUBCYCLE_INTERMEDIATE: 'strobe1.2.subcycle_intermediate',
  STROBE1_2_SUBCYCLE: 'strobe1.2.subcycle',
  STROBE1_3_SUBCYCLE_INTERMEDIATE: 'strobe1.3.subcycle_intermediate',
  STROBE1_3_SUBCYCLE: 'strobe1.3.subcycle',
  STROBE1_4_SUBCYCLE_INTERMEDIATE: 'strobe1.4.subcycle_intermediate',
  STROBE1_4_SUBCYCLE: 'strobe1.4.subcycle',
});
export type StateType = $Values<typeof State>;
